### ISSUE TITLE
Unable to connect using service account token

### ISSUE THREAD

**Issue by Raj123456788** [1Password/connect-sdk-js#114]
### Your environment

SDK Version:
1.4.1

Connect Server Version:

OS:
Win 10

Node Version:
18.19
## What happened?

Hello There,
I am trying to use the service token for onepasswordconnect Api. Can you please provide me an example as to how ai can use it?
### Use cases
 No serviceurl ir token but connect to sdk isi g service account token

## What did you expect to happen?
Should be able to connect 
## Steps to reproduce
Use service account token only to connect

**Comment by volodymyrZotov** [comment]
Hi @Raj123456788👋. This SDK doesn't support service account tokens and works only with Connect.

Our team is working on [another JS SDK](https://github.com/1Password/onepassword-sdk-js). It's currently in beta. That one allows you to use it with service accounts.
