### ISSUE TITLE
options.response.data is not guaranteed to exist when client request fails

### ISSUE THREAD

**Issue by petetnt** [1Password/connect-sdk-js#14]
### Your environment

SDK Version: 1.0.0.

Connect Server Version: 1.1.0

OS:MacOS

Node Version: 16.0.0

## What happened?

If the client request fails for some reason, this catch handler will be run:

https://github.com/1Password/connect-sdk-js/blob/main/src/lib/client.ts#L69

However, in my case the handler actually throws because data is not available:

```bash
/foo/node_modules/@1password/connect/dist/lib/client.js:87
        (error) => Promise.reject(error.response.data));
                                                 ^

TypeError: Cannot read property 'data' of undefined
```

## What did you expect to happen?

Error should try to define what went wrong in specific way, by at least exposing the http error code and the relevant message

## Steps to reproduce
Create foo.mjs

```js
import { OnePasswordConnect } from '@1password/connect';

const op = OnePasswordConnect({
	serverURL: 'http://x',
	token: 'x',
	keepAlive: true,
});

async function foo() {
	console.log(await op.listVaults())
}

console.log(foo())
```

Run with

```bash
node foo.mjs
```

**Comment by verkaufer** [comment]
Hi @petetnt! Thank you for reporting this issue.

This is definitely something the SDK should raise with a friendlier message. I'll make sure this is addressed in our next release.
