### ISSUE TITLE
new items generation recipe is broken

### ISSUE THREAD

**Issue by kesor** [1Password/connect-sdk-js#32]
When the API call is made, `JSON.stringify` does not know how to stringify JavaScript `Set` objects. Thus the recipe is invalid and the server logs an error and returns a `400`.

https://github.com/1Password/connect-sdk-js/blob/859064bd48262e7c14dbace8267d70bff8111b2e/src/model/generatorRecipe.ts#L21

Logged error was:

```
op-connect-api     | {"log_message":"(E) Server: (invalid JSON sent by client), json: cannot unmarshal object into Go struct field GeneratorRecipe.fields.recipe.characterSets of type []string","timestamp":"2021-09-04T23:43:26.83597448Z","level":1,"scope":{"request_id":"b8f71f5c-01e9-4d36-a997-56d33f99d2df","jti":"do5lfdfnl7bf5td7n45twobihu"}}
```

As you can see the characterSets is empty, even though the original request has all three options of letters, digits and symbols.

**Comment by hculea** [comment]
Hi there,

Thank you for reporting. We'll take a look at this issue and get back to you about it shortly.
